# tutorial4

In [26]:
import numpy as np
#no division by zero error
a=np.array([1,2,3])
a/0

/Users/roni/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([inf, inf, inf])

In [27]:
#nan values
a=np.array([1,0,100])
a/0


/Users/roni/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/roni/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([inf, nan, inf])

In [28]:
np.nan==np.nan

False

In [29]:
np.isnan(np.nan)

True

In [33]:
#integer overflow
a=np.array([1,10,20,130],dtype=np.int8)
a

array([   1,   10,   20, -126], dtype=int8)