# tutorial 13

In [38]:
import numpy as np

In [39]:
a=np.array([1,2,2,12,20])

In [40]:
a

array([ 1,  2,  2, 12, 20])

In [41]:
#view() in numpy

b=a.view()

In [42]:
b

array([ 1,  2,  2, 12, 20])

In [43]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [44]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [45]:
b[0]

1

In [46]:
a[0]

1

In [47]:
b[0]=10

In [48]:
b

array([10,  2,  2, 12, 20])

In [49]:
a

array([10,  2,  2, 12, 20])

In [50]:
#copy() in numpy
a

array([10,  2,  2, 12, 20])

In [51]:
c=a.copy()

In [52]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [53]:
c[4]=100

In [54]:
c

array([ 10,   2,   2,  12, 100])

In [55]:
a

array([10,  2,  2, 12, 20])

In [57]:
#examples of view :


a=np.array([1,7,9,10,12,40,23])

In [58]:
b=a[1:3]

In [59]:
b

array([7, 9])

In [60]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [61]:
b[0]

7

In [62]:
b[1]

9

In [63]:
b[0]=12

In [64]:
a

array([ 1, 12,  9, 10, 12, 40, 23])