# tutorial 2

In [51]:
#how to create numpy array
import numpy as np
a=np.array([1,2,3])

In [45]:
#how to display array elements
a

array([1, 2, 3])

In [84]:
#accessing array elements by index
a[-1]

3

In [47]:
#type of numpy object
type(a)

numpy.ndarray

In [49]:
#python array creation
import array
b=array.array("i",[1,2,4])

In [50]:
#python array object type
type(b)

array.array

In [52]:
#dimension of numpy array
a.ndim

1

In [53]:
#shape of numpy array
a.shape

(3,)

In [ ]:
#how to create 2d numpy array 

In [59]:
c=np.array([[1,2,3],[1,2,3],[1,2,2]])

In [60]:
c

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 2]])

In [61]:
c.ndim

2

In [62]:
c.shape

(3, 3)

In [63]:
#how to create 3d numpy array

d=np.array([[[1, 2, 3],
       [1, 2, 3],
       [1, 2, 2]],[[1, 2, 3],
       [1, 2, 3],
       [1, 2, 2]]])

In [64]:

d

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 2]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 2]]])

In [65]:
d.ndim

3

In [67]:
d.shape

(2, 3, 3)

In [69]:
#find how many elements 
d.size

18

In [70]:
a.size

3

In [71]:
#single element size in bye
a.itemsize

8

In [72]:
a.dtype

dtype('int64')

In [73]:
#create numpy array with user defined data type

a=np.array([1,2,3],dtype=np.int32)

In [74]:
a

array([1, 2, 3], dtype=int32)

In [75]:
a.itemsize

4

In [76]:
#create numpy array with string

b=np.array(["roni","saikat","amit"])

In [77]:
b

array(['roni', 'saikat', 'amit'], dtype='<U6')

In [78]:
b.dtype

dtype('<U6')

In [79]:
c=np.array([1.5,6.7])

In [80]:
c.dtype

dtype('float64')