# tutorial 5

In [15]:
import numpy as np

In [20]:
a=np.zeros([2,3],dtype=np.int32)

In [21]:
a

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [19]:
a.dtype

dtype('float64')

In [22]:
np.ones??

In [25]:
b=np.ones([4,4],dtype=np.int32)

In [26]:
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [32]:
np.zeros_like??


In [28]:
c=np.array([[1,2,2],[1,2,2]])

In [29]:
c

array([[1, 2, 2],
       [1, 2, 2]])

In [30]:
d=np.zeros_like(c)

In [31]:
d

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
np.ones_like??

In [34]:
e=np.ones_like(c)

In [35]:
e

array([[1, 1, 1],
       [1, 1, 1]])