# tutorial 8

In [13]:
import numpy as np

In [14]:
a=np.array([1,3,7,9])

In [15]:
a[2]

7

In [16]:
a[3]

9

In [17]:
a[-1]

9

In [18]:
a[-2]

7

In [19]:
a=np.arange(10).reshape(5,2)

In [20]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
a[3,1]

7

In [22]:
a[4,1]

9

# slicing

In [24]:
a=np.arange(12)

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#id slicing

In [27]:
#first index is inclusive and last index will be exclusive
a[:6]

array([0, 1, 2, 3, 4, 5])

In [28]:
#to get the complete numpy array 
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
#2d array slicing 1st example
a=np.arange(12).reshape(3,4)

In [33]:
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a[0:1,0:2]

array([[0, 1]])

In [ ]:
#2d array slicing 2nd example

In [35]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [ ]:
#2d array slicing 3rd example

In [36]:
a[:2,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [37]:
#2d array slicing 4th example

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
#2d array slicing 5th example
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])