# tutorial 9

In [18]:
import numpy as np
a=np.arange(12)
a=a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
#slicing will be applied first on row level and then column
#starts with zero index in row level and ends on first index , but first index is exclusive that is why it only returns row at  first index 
a[:1,:]

array([[0, 1, 2, 3]])

In [10]:
#slicing will be applied first on row level and then column
#starts with zero index in row level and ends on first index , but first index is exclusive that is why it only returns row at  first index 
#starts with zero index at cloumn level and ends with first index , but first index is exclusive that is why it returns only element from zero index
a[:1,:1]

array([[0]])

In [11]:
#with get item call, collapses one dimension 

a[1]

array([4, 5, 6, 7])

In [14]:
#mixed up with get item call(slicing call & get item call)
a[:1,1]

array([1])

In [17]:
#mixed up with get item call( two get item call)
a[1,1]

5

In [21]:
#mixed up with get item call(get item call & slicing call)
a[1,:1]

array([4])