# tutorial 8

# tutorial 8

In [3]:
#indexing
import numpy as np
a=np.array([1,2,3,4])
a[3]


4

In [4]:
a[2]

3

In [5]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [6]:
#slicing
a

array([1, 2, 3, 4])

In [9]:
#1st positional index is inclusive & last positional index is exclusive
#not mentioning anything at 1st index means always consider first element
#not mentioning anything at last index means always consider the last element

a[:2]

array([1, 2])

In [8]:
a[1:3]

array([2, 3])

In [10]:
a[:]

array([1, 2, 3, 4])

In [11]:
a[1:]

array([2, 3, 4])

In [34]:
#example:1
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a[:1,:2]

array([[0, 1]])

In [37]:
#example:2
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [41]:
#example:3
a[:2,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
#example:4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
#example:5
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
a[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])