# tutorial 6

In [25]:
import numpy as np

In [34]:
#np.arange with deafult start and step
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#np.arange with start and step mentioned
a=np.arange(5,10,2)
a

array([5. , 7.6])

In [38]:
#np.arange with custom start and default step
a=np.arange(start=1,stop=20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [42]:
#np.arange with start and step mentioned in float
a=np.arange(5,10,.02)
a

array([5.  , 5.02, 5.04, 5.06, 5.08, 5.1 , 5.12, 5.14, 5.16, 5.18, 5.2 ,
       5.22, 5.24, 5.26, 5.28, 5.3 , 5.32, 5.34, 5.36, 5.38, 5.4 , 5.42,
       5.44, 5.46, 5.48, 5.5 , 5.52, 5.54, 5.56, 5.58, 5.6 , 5.62, 5.64,
       5.66, 5.68, 5.7 , 5.72, 5.74, 5.76, 5.78, 5.8 , 5.82, 5.84, 5.86,
       5.88, 5.9 , 5.92, 5.94, 5.96, 5.98, 6.  , 6.02, 6.04, 6.06, 6.08,
       6.1 , 6.12, 6.14, 6.16, 6.18, 6.2 , 6.22, 6.24, 6.26, 6.28, 6.3 ,
       6.32, 6.34, 6.36, 6.38, 6.4 , 6.42, 6.44, 6.46, 6.48, 6.5 , 6.52,
       6.54, 6.56, 6.58, 6.6 , 6.62, 6.64, 6.66, 6.68, 6.7 , 6.72, 6.74,
       6.76, 6.78, 6.8 , 6.82, 6.84, 6.86, 6.88, 6.9 , 6.92, 6.94, 6.96,
       6.98, 7.  , 7.02, 7.04, 7.06, 7.08, 7.1 , 7.12, 7.14, 7.16, 7.18,
       7.2 , 7.22, 7.24, 7.26, 7.28, 7.3 , 7.32, 7.34, 7.36, 7.38, 7.4 ,
       7.42, 7.44, 7.46, 7.48, 7.5 , 7.52, 7.54, 7.56, 7.58, 7.6 , 7.62,
       7.64, 7.66, 7.68, 7.7 , 7.72, 7.74, 7.76, 7.78, 7.8 , 7.82, 7.84,
       7.86, 7.88, 7.9 , 7.92, 7.94, 7.96, 7.98, 8.

In [69]:
#np.linspace with endpoint flase
a=np.linspace(1,100,10,endpoint=False)

In [68]:
a

array([ 1. , 10.9, 20.8, 30.7, 40.6, 50.5, 60.4, 70.3, 80.2, 90.1])

In [71]:
#np.linspace with endpoint true by default
a=np.linspace(1,100,10)
a

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])