# tutorial 3

In [1]:
import numpy as np

In [2]:
#1d array
a=np.array([1,2,3])

In [3]:
a.ndim

1

In [4]:
a.shape

(3,)

In [5]:
#2d array
#every element of a 2d array it self a 1d array

b=np.array([a,a ,a ])

In [6]:
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
b.ndim

2

In [8]:
b.shape

(3, 3)

In [9]:
#3d array
#every element of a 3d array is itself a 2d array

c=np.array([b,b,b])

In [10]:
c

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [11]:
c.shape

(3, 3, 3)

In [12]:
#4d array
#every element will be a 3d array itself

d=np.array([c,c,c,c])

In [13]:
d

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])

In [14]:
d.ndim

4

In [15]:
#shape
d.shape

(4, 3, 3, 3)

In [16]:
#5d array
#every element will be 4d array itself

e=np.array([d,d])

In [17]:
e

array([[[[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]],



       [[[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]],


        [[[1,

In [18]:
e.ndim 

5

In [19]:
e.shape

(2, 4, 3, 3, 3)