# tutorial 3

In [22]:
#1d array
a=np.array([1,2,3])
a.shape

(3,)

In [23]:
#2d array
#every element in a 2d array itself a 1d array

b=np.array([ a,a,a     ])


In [24]:
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [25]:
#how many (2-1)=1 d array
b.shape

(3, 3)

In [26]:
#3darray
#every element in a 2d array itself a 1d array
c=np.array([ b,b    ])

In [27]:
c

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [ ]:
#how many 2d array ,in every 2d array how many 1d array , in each 1d array how many elements.

In [28]:
c.shape

(2, 3, 3)

In [ ]:
(2,3,3)

In [29]:
#4d array
#every element in a 4d array itself a 3d array
d=np.array([c,c,c])

In [32]:
#how many 3d arrays ,in every 3d array how many 2d array ,in every 2d array how many 1d array , in each 1d array how many elements.
d.shape

(3, 2, 3, 3)

In [31]:
(3,2,3,3)

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])

In [33]:
#5d array
#every element in a 5d array itself a 4d array
e=np.array([d,d])


In [34]:
e.ndim

5

In [35]:
e

array([[[[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]],



       [[[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]]])

In [ ]:
#how many 4d array ,in every 4d array how many 3d arrays ,in every 3d array how many 2d array ,in every 2d array how many 1d array , in each 1d array how many elements.

In [36]:
e.shape

(2, 3, 2, 3, 3)