# tutorial 10

In [20]:
import numpy as np

In [21]:
a=np.arange(0,24,1)

In [23]:
a=a.reshape(2,4,3)

In [29]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [25]:
#exercise:1
a[:1,:2,:2]

array([[[0, 1],
        [3, 4]]])

In [27]:
#exercise :2
a[:1,2:,:]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [30]:
#exercise:3
a[1:,1:,1:]

array([[[16, 17],
        [19, 20],
        [22, 23]]])

In [32]:
#exercise:4
a[:1,2:3,:2]

array([[[6, 7]]])