# tutorial 14

In [6]:
import numpy as np

In [14]:
#example 1
a=np.arange(6)**2
a[[1,4]]

array([ 1, 16])

In [24]:
#example 2
b=np.arange(12).reshape(4,3)
b[[1,2,3],[0,1,2]]

array([ 3,  7, 11])

In [25]:
#example 3
c=np.arange(12).reshape(2,3,2)

In [28]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [30]:
c[[0,1,0],[2,1,2],[0,1,1]]

array([4, 9, 5])