In [1]:
import numpy as np

In [263]:
a=list(range(10000000))

In [6]:
list_sum=sum(a)

In [7]:
list_sum

49995000

In [10]:
np_sum=np.sum(b)

In [12]:
np_sum

49995000

In [20]:
%timeit sum(a)

69.4 ms ± 992 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
%timeit np.sum(b)

8.08 ms ± 218 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# so why numpy is faster than list ?

in case of list it is holding the address of the data and in case of numpy it holding the actual data this is the main reason 

In [21]:
a=np.array([1,-1,0,0])

In [22]:
a

array([ 1, -1,  0,  0])

In [23]:
a.dtype

dtype('int64')

In [24]:
a.shape

(4,)

In [25]:
a.ndim

1

In [26]:
a.size

4

In [27]:
a.itemsize

8

In [29]:
1/0

ZeroDivisionError: division by zero

In [30]:
a/0

/Users/roni/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/roni/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf, -inf,  nan,  nan])

In [31]:
a=np.array([[1,2],[2,4]])

In [32]:
a

array([[1, 2],
       [2, 4]])

In [34]:
a.ndim

2

In [35]:
a.shape

(2, 2)

In [36]:
a.size

4

In [37]:
a.itemsize

8

In [44]:
a=np.arange(0,50,2).reshape(5,5)

In [47]:
(a.T).T

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [50]:
a=np.linspace(0,15,9)

In [51]:
a

array([ 0.   ,  1.875,  3.75 ,  5.625,  7.5  ,  9.375, 11.25 , 13.125,
       15.   ])

In [52]:
np.logspace(0,15,8)

array([1.00000000e+00, 1.38949549e+02, 1.93069773e+04, 2.68269580e+06,
       3.72759372e+08, 5.17947468e+10, 7.19685673e+12, 1.00000000e+15])

In [68]:
a=np.zeros([2,2,3],dtype=float)

In [69]:
a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [70]:
a+8

array([[[8., 8., 8.],
        [8., 8., 8.]],

       [[8., 8., 8.],
        [8., 8., 8.]]])

In [72]:
a=np.empty([1,2],dtype=float)

In [73]:
a

array([[0., 0.]])

In [75]:
a.dtype

dtype('float64')

In [76]:
a.astype("int64")

array([[0, 0]])

In [81]:
a=np.array([1,2,4,16],dtype="int8")

In [82]:
a

array([ 1,  2,  4, 16], dtype=int8)

In [83]:
b=np.array([1,2,4,16])

In [84]:
b

array([ 1,  2,  4, 16])

In [86]:
a*10000

array([ 10000,  20000, -25536,  28928], dtype=int16)

In [87]:
10000*4

40000

In [90]:
a=np.arange(0,90,1).reshape(3,5,6)

In [91]:
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

In [93]:
a[0,0,0]

0

In [94]:
a[1,1,1]

37

In [95]:
a[2,2,3]

75

In [96]:
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

In [97]:
a[:,:,:]

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

In [98]:
a[1:,:,:]

array([[[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

In [118]:
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

In [107]:
a[1,0,:]

array([30, 31, 32, 33, 34, 35])

In [108]:
a[1,3:,:]

array([[48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [113]:
a[0,2:4,5:]

array([[17],
       [23]])

In [117]:
a[1,1,1]

37

In [120]:
a[[1,2,0],[1,3,2],[1,3,3]]

array([37, 81, 15])

In [121]:
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

In [123]:
mask=[a%2==0]

In [124]:
a[mask]

/Users/roni/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88])

In [125]:
np.where(mask)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2]),
 array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 0, 0, 0, 1, 1, 1, 2,
        2, 2, 3, 3, 3, 4, 4, 4, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4,
        4]),
 array([0, 2, 4, 0, 2, 4, 0, 2, 4, 0, 2, 4, 0, 2, 4, 0, 2, 4, 0, 2, 4, 0,
        2, 4, 0, 2, 4, 0, 2, 4, 0, 2, 4, 0, 2, 4, 0, 2, 4, 0, 2, 4, 0, 2,
        4]))

In [127]:
a=np.arange(0,90)

In [142]:
mask=[a%5==0]

In [143]:
np.where(mask)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
        85]))

In [144]:
mask

[array([ True, False, False, False, False,  True, False, False, False,
        False,  True, False, False, False, False,  True, False, False,
        False, False,  True, False, False, False, False,  True, False,
        False, False, False,  True, False, False, False, False,  True,
        False, False, False, False,  True, False, False, False, False,
         True, False, False, False, False,  True, False, False, False,
        False,  True, False, False, False, False,  True, False, False,
        False, False,  True, False, False, False, False,  True, False,
        False, False, False,  True, False, False, False, False,  True,
        False, False, False, False,  True, False, False, False, False])]

In [131]:
a[mask]

/Users/roni/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88])

In [149]:
a[np.where(a%5==0)]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85])

In [135]:
np.where?


In [138]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [151]:
a.max()

89

In [152]:
a.min()

0

In [153]:
a.argmin()

0

In [154]:
a.argmax()

89

In [161]:
a=np.ones([1,8],dtype=int)

In [162]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1]])

In [171]:
a[0,4]=a[0,4]*2

In [173]:
a[0,7]=5

In [174]:
a

array([[1, 1, 2, 4, 2, 1, 1, 5]])

ValueError: object too deep for desired array

In [178]:
a

array([[1, 1, 2, 4, 2, 1, 1, 5]])

In [184]:
c,d=(np.unique(a,return_counts=True))

In [186]:
d

array([4, 2, 1, 1])

In [187]:
dict(zip(c,d))


{1: 4, 2: 2, 4: 1, 5: 1}

In [196]:
list1=list(a)

In [200]:
type(list1)

list

In [234]:
c=np.genfromtxt("numtest.csv",dtype=str,skip_header=1,delimiter=',')

In [235]:
c

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U1')

In [216]:
c[0]

'1,2,3'

In [217]:
c[1]

'4,5,6'

In [218]:
c[2]

'7,8,9'

In [221]:
c.argmax()

8

In [223]:
c.argmin()

0

In [227]:
c[2,2]

'9'

In [230]:
c=c.flatten()

In [231]:
c[8]

'9'

In [232]:
c

array(['1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

In [236]:
c

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U1')

   c

In [258]:
c

array([['1', '1', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U1')

In [259]:
np.unravel_index(np.argmin(a,axis=None),a.shape)

(0, 0)

In [260]:
c[0,0]

'1'

In [261]:
b=c[0,0]

In [262]:
c[np.where(c==b)]

array(['1', '1'], dtype='<U1')